spring:
    application:
        name: notification-service
    jackson:
        # Global setting to not return null objects in JSON responses
        default-property-inclusion: NON_NULL
    sleuth:
        sampler:
            probability: 1.0
        propagation:
            type: W3C
    # zipkin:
    #     enabled: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-service
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.value.default.type: net.binarypaper.notificationservice.order.Order
        listener:
            concurrency: 4
#            ack-mode: MANUAL

server:
    port: 8082

management:
    server:
        port: 8582
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            probes:
                enabled: true

application:
    kafka:
        topic: order-queue

logging:
    level:
        org.springframework: ERROR
        org.apache.kafka: ERROR