global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'app-server:8580'
  - job_name: product-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'app-server:8581'
  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'app-server:8582'