version: "3.9"
networks:
  backend:
    driver: bridge
services:
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
      - target: 3030
        published: 3030
      - target: 9092
        published: 9092
    environment:
      ADV_HOST: 127.0.0.1
      BROKER_PORT: 9092

  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true

  elasticsearch:
    image: elasticsearch:8.2.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - target: 9200
        published: 9200
    networks:
      - backend

  kibana:
    image: kibana:8.2.3
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - target: 5601
        published: 5601
    networks:
      - backend
    depends_on:
      - elasticsearch
    

  logstash:
    image: logstash:8.2.3
    ports:
      - target: 5009
        published: 5009
    networks:
      - backend
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v2.36.2
    ports:
      - target: 9090
        published: 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend
    extra_hosts:
      - "app-server:${app_server_ip}"

  grafana:
    image: grafana/grafana:9.0.2
    ports:
      - target: 3000
        published: 3000
    networks:
      - backend
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus